### ISSUE TITLE
Should the button method be static?

### ISSUE THREAD

**Issue by ditikos** [thenbrent/paypal-digital-goods-php-examples#1]
In your example, you have a purchase premade and only after that you can create a button for submit.

Suppose I have a form with four radio buttons (which one must be selected) which approach do I use to go to the next step (i.e. the purchase?)

**Comment by thenbrent** [comment]
Take a look at the _Separate Checkout_ [example](https://github.com/thenbrent/paypal-digital-goods-php-examples/blob/master/example-subscription-checkout.php). It's for a subscription, but demonstrates how to add an intermediate step between the customer clicking the button and requesting the checkout token from PayPal.

You can determine during this intermediate step what amount to set.
