### ISSUE TITLE
Paypal Digital Goods library examples, half window shown on Firefox

### ISSUE THREAD

**Issue by Ivo216** [thenbrent/paypal-digital-goods-php-examples#2]
Hi Brent, in your Paypal Digital Goods library examples, with Firefox 37 for Windows 7, I can see only half of the window, as attached.
However, Internet Explorer and Chrome behave fine.
![half-window](https://cloud.githubusercontent.com/assets/3462955/7332334/2f255012-eb3b-11e4-8fc9-29151ed7c192.JPG)

**Comment by thenbrent** [comment]
Pretty sure that's in the iframe from PayPal, so it would need to be fixed at PayPal's end. I think the best place to lodge a bug report with PayPal is here: http://ppmts.custhelp.com/
